name: Deploy to AWS

on:
  push:
    branches: [ aws ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: cashclimb-repo
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

      - name: Deploy to AWS App Runner
        id: deploy-apprunner
        uses: awslabs/amazon-app-runner-deploy@main
        with:
          service: cashclimb-backend
          image: ${{ steps.build-image.outputs.image }}
          access-role-arn: ${{ secrets.AWS_ROLE_ARN }}
          region: us-east-2
          cpu: 1
          memory: 2
          port: 8000
          env-vars: |
            COINMARKETCAP_API_KEY=${COINMARKETCAP_API_KEY}
            ETHERSCAN_API_KEY=${ETHERSCAN_API_KEY}
            FIREBASE_API_KEY=${FIREBASE_API_KEY}
            OPENAI_APIKEY=${OPENAI_APIKEY}
            AWS_REGION=us-east-2
            AWS_S3_BUCKET=cashclimb-wallets
            AWS_COGNITO_USER_POOL_ID=${{ secrets.AWS_COGNITO_USER_POOL_ID }}
            AWS_COGNITO_CLIENT_ID=${{ secrets.AWS_COGNITO_CLIENT_ID }}
